version: '3'
services:
    srv:
        image: node:alpine
        working_dir: /app
        ports:
            - 3000:3000
        volumes:
            - .:/app
        command: npm run start:dev

    bdd:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=secret
